{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow-health-dashboard.fullname" . }}-backend
  labels:
    {{- include "airflow-health-dashboard.backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "airflow-health-dashboard.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.backend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "airflow-health-dashboard.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "airflow-health-dashboard.serviceAccountName" . }}
      {{- if .Values.backend.airflow.hostAliases }}
      hostAliases:
        {{- toYaml .Values.backend.airflow.hostAliases | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
      - name: backend
        securityContext:
          {{- toYaml .Values.backend.securityContext | nindent 10 }}
        image: {{ include "airflow-health-dashboard.backend.image" . }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.backend.service.targetPort }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "airflow-health-dashboard.fullname" . }}-config
        env:
        {{- if .Values.backend.vault.enabled }}
        - name: BASH_ENV
          value: /vault/secrets/secrets
        {{- else }}
        {{- if .Values.backend.airflow.authMethod }}
        {{- if eq .Values.backend.airflow.authMethod "basic" }}
        - name: AIRFLOW_USERNAME
          value: {{.Values.backend.airflow.username }}
        - name: AIRFLOW_PASSWORD
          value: {{.Values.backend.airflow.password }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.backend.livenessProbe.enabled }}
        livenessProbe:
          {{- toYaml (omit .Values.backend.livenessProbe "enabled") | nindent 10 }}
        {{- end }}
        {{- if .Values.backend.readinessProbe.enabled }}
        readinessProbe:
          {{- toYaml (omit .Values.backend.readinessProbe "enabled") | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
